### ISSUE TITLE
Exclude non-mov files from upload

### ISSUE THREAD

**Issue by tfe** [epicsf/epic-video-archive#2]
There's a bunch of spotlight and trash files getting uploaded... I've tried in the past to disable spotlight and trash on these drives but it's a losing battle. How about just slapping a condition on here? https://github.com/epicsf/epic-video-archive/blob/master/s3_manager.py#L34

**Comment by tknickman** [comment]
Yep good call, I'll do this tonight.

**Comment by tknickman** [comment]
@tfe instead of filtering for video file extensions I just striped out hidden files and folders.
