### ISSUE TITLE
Progress indicator would be nice

### ISSUE THREAD

**Issue by tfe** [epicsf/epic-video-archive#5]
Can we just print the percentage of total file size complete when we log the part upload? Just part size times part number divided by total file size. I find myself manually multiplying the part number by the part size to figure it out.

**Comment by tknickman** [comment]
Added the following stats to the upload process:

Percent Complete
Previous Part Upload Time
Average Part Upload Time
Estimated Time Of Completion

**Comment by tfe** [comment]
So hot.
